### ISSUE TITLE
"Hello everyone" in Python

### ISSUE THREAD

**Issue by MoskalykA** [MoskalykA/code-database#1]
Just the title

**Comment by MoskalykA** [comment]
> Is it asking to print "hello everyone" in python?

yes

**Comment by Ashpreetwadhwa** [comment]
I want to this task @MoskalykA

**Comment by MoskalykA** [comment]
Good work ! <3

**Comment by recksoldier** [comment]
I want this task!

**Comment by MoskalykA** [comment]
> I want this task!

One person already has it but you can do other things in Python!

**Comment by MoskalykA** [comment]
> Sure!, Im aa newbie here but very fluent in python, how can I get other tasks assigned to me?

You have to clone the directory ([https://github.com/MoskalykA/code-database/fork](https://github.com/MoskalykA/code-database/fork)) then create a branch (`git checkout -b branch-name`) then make your changes, assign them to a message (`git add . & git commit -m "message"`) and send them (`git push origin branch-name`)

**Comment by Ashwinip343** [comment]
Where is "Hello everyone" in cpp issue that I was assigned?
